_target_: src.autolabel.zero_shot.GroundingDinoAutoLabeler
model_name: IDEA-Research/grounding-dino-base
prompt: "vehicle."
box_threshold: 0.15
text_threshold: 0.15
nms_iou_threshold: 0.5
containment_threshold: 0.8
device: cuda
