defaults:
  - autolabeler: gdino_b015_t015_nms05_c08
  - temporal_filter: default
  - _self_

frames_dir: data/datasetv2/images/train
labels_dir: data/datasetv2/labels_greedy/train
labels_clean_dir: data/datasetv2/labels_greedy/train_clean
labels_debug_dir: data/datasetv2/labels_greedy_debug
save_debug: true
class_id: 0
